# These are supported funding model platforms

custom: ['https://cdn.jsdelivr.net/gh/athlonreg/athlonreg.github.io/medias/reward/wechatpay.jpg', 'https://cdn.jsdelivr.net/gh/athlonreg/athlonreg.github.io/medias/reward/alipay.jpg']
